config/routes.rb
Rails.application.routes.draw do

  get 'cookies/example_1'

  get 'cookies/example_2'

  get 'cookies/example_3'

  get 'secret/public_info'

  get 'secret/secret'

  root 'sessions#new'

  get 'reviews/index'

  get 'reviews/create'

  get 'reviews/new'

  get 'static_pages/home'

  get '/login', to: 'sessions#new'

resources :sessions, only: [:new, :create, :destroy]

resources :users
resources :stores
resources :drinks
resources :comments
resources :drink_prices
resources :category
resources :static_pages
delete '/logout', to: 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :drinks
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :store
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  has_many :prices
  has_many :stores, through: :prices

  def price(store_id)
    drink = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink
      drink.price
    else
      nil
    end
  end

  def set_price(store_id, new_price)
    drink = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink
      drink.price = new_price
      drink.save
    end
  end

   def drink_price(store_id)
    drink_price = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink_price
      drink_price
    else
      nil
    end
  end

end

app/models/drink_price.rb
class DrinkPrice < ActiveRecord::Base
  belongs_to :store
  belongs_to :drink
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :drink_prices
  has_many :drinks, through: :drink_prices
  has_many :comments


  geocoded_by :address
  after_validation :geocode, :if => :address_changed?


end

app/models/user.rb
class User < ActiveRecord::Base

 has_secure_password
 validates :email, presence: true, uniqueness: true

 # geocoded_by :ip_address,
 #  :latitude => :lat, :longitude => :lon
 # after_validation :geocode

 def ip_address
  require 'socket'
  Socket::getaddrinfo(Socket.gethostname,"echo",Socket::AF_INET)[0][3]
 end

end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def example_1
    cookies[:user_name] = 'david'
  end

  def example_2
    cookies[:reference_to_keep_for_a_while] = { value: 'XJ-122', expires: 1.year.from_now }
  end

  def example_3
    puts cookies.inspect
    cookies.delete :user_name
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :authenticate

  def index
    @drinks = Drink.all
  end

  def show
    @drink = Drink.find(params[:id])
  end

  def edit
    @drink = Drink.find(params[:id])
  end

  def update
    @drink = Drink.find(params[:id])
    @drink.update_attributes(drink_params)
    redirect_to drinks_path
  end

  def new
    @drink = Drink.new
  end

 def create
  @drink = Drink.new(drink_params)
  if @drink.save
   redirect_to drinks_path
  else
   render 'new'
  end
 end

  def destroy
    drink = Drink.find(params[:id])
    drink.destroy
    redirect_to drinks_path
  end

  private

  def drink_params
    params.require(:drink).permit(:name, :photo_url,)
  end
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController
  before_action :authenticate, only: :secret

  def public_info
    render text: "You can see this text because the controller method is not protected by a before_action in the controller"
  end

  def secret
    render text: "You can only see this text when you are logged in because this method in the controller is protected by a before_action"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = Store.find(params[:id])
    # @drink_price = DrinkPrice.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    @store.update_attributes(store_params)
    redirect_to stores_path
  end

  def  new
    @store = Store.new
  end

 def create
  @store = Store.new(store_params)
  if @store.save
   redirect_to stores_path
  else
   render 'new'
  end
 end

 def maps
     url = "https://maps.googleapis.com/maps/api/js?key="
     key = ENV['GOOGLE_MAPS']
     @endpoint = url + key
 end

  def destroy
    store = Store.find(params[:id])
    store.destroy
    redirect_to stores_path
  end

  private

  def store_params
    params.require(:store).permit(:name, :address, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: :edit

 def index
  @users = User.all
 end

 def show

 end

 def new
  @user = User.new
 end

 def create
  @user = User.new(user_params)
  if @user.save
   redirect_to login_path
  else
   render 'new'
  end
 end

 private

 def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/drink_prices_helper.rb
module DrinkPricesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drinks/create.html.erb
<h1>create new drink</h1>

app/views/drinks/edit.html.erb
<h1>drink edit</h1>


<div id="red">
 <%= form_for @drink do |f| %>
 <% if @drink.errors.any? %>
 <% end %>
   <div class="error_messages" >
   <%= f.label :name %>
   <%= f.text_field :name %>
 </div>
<br>
 <div class="field">
   <%= f.label :photo_url %>
   <%= f.text_field :photo_url %>
 </div>

<br>
 <div class="actions"><%= f.submit %></div>

 <p><%= link_to "Drinks", drinks_path %></p></div>


<% end %>

app/views/drinks/index.html.erb
<div class="container">


<h1>Listing Drinks</h1>
<button type="button" class="btn btn-primary"><%= link_to 'New Drink', new_drink_path %></button>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @drinks.each do |drink| %>
  <tr>
    <td><%= drink.name %></td>

    <td><img id="drinkpic" src="<%= drink.photo_url %>" alt=""></td>


    <td>$$</td>
    <td><%= link_to 'Show', drink %></td>
    <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
    <td><%= link_to 'Destroy', drink, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>



</div>

app/views/drinks/new.html.erb
<h1>New Drink .png file prefered</h1>
<div id="red">
<%= form_for @drink do |f| %>
  <% if @drink.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @drink.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>
  <br>
  <div class="actions"><%= f.submit %></div>
<% end %>

<p><%= link_to "Drinks", drinks_path %></p>
</div>

app/views/drinks/show.html.erb
<h1><%= @drink.name %></ph1>
<p><img id="drinkpic" src="<%= @drink.photo_url %>" ></p>

app/views/stores/create.html.erb
<h1>create stores</h1>

app/views/stores/edit.html.erb
<h1>store edit</h1>

<div id="red">


<div id="edit">
<%= form_for @store do |f| %>
<% if @store.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @store.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<br>
<div class="field">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div>
<br>
<div class="actions"><%= f.submit %></div>
<% end %>

<p><%= link_to "Stores", stores_path %></p>

</div>
</div>

app/views/stores/index.html.erb
<h1>Nearby Stores</h1>


<script>
var user_posish = function(){
  navigator.geolocation.getCurrentPosition(c);
  return false;
}

var c = function(pos)  {
var lat    = pos.coords.latitude,
    long   = pos.coords.longitude,
    coords = lat + ', ' + long;

document.getElementById('google_map').setAttribute('src', 'https://maps.google.com/?q=' + coords +'&z=60&output=embed')
}

user_posish();
</script>


<div id="store_map">
  <iframe id="google_map" width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com?output=embed"></iframe>
</div>



<h2><button type="button" class="btn btn-success"><%= link_to 'New Store', new_store_path %></button></h2>


<div id="storetable" class="container">


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @stores.each do |store| %>
  <tr>
    <td><button type="button" class="btn btn-success"><%= link_to store.name, store_path(store), method: :get %></button></td>
    <td><%= store.address %></td>
    <td>Miles</td>

    <td><button type="button" class="btn btn-success"><%= link_to 'Edit', edit_store_path(store) %></button></td>
    <td><button type="button" class="btn btn-danger"><%= link_to 'Delete', store, method: :delete,
                                    data: { confirm: 'Are you sure?' } %></button></td>


  </tr>
<% end %>
</table>

<br>


</div>

app/views/stores/new.html.erb
<h1>New Store</h1>
<div id="red">
<%= form_for @store do |f| %>
  <% if @store.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @store.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <br>
  <div class="actions"><%= f.submit %></div>
<% end %>

<p><%= link_to "Stores", stores_path %></p>
</div>

app/views/stores/show.html.erb
<div  class="container">

<h1><%= @store.name %></h1>
<p><%= @store.address %></p>

<style type="text/css">
      html, body, #map-canvas
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_KEY'] %>">
    </script>
    <script type="text/javascript">
      function initialize() {
        var store_location = {lat: <%= @store.latitude %>, lng: <%= @store.longitude %>};
        var mapOptions = {
          center: store_location,
          zoom: 15
        };

        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        var marker = new google.maps.Marker({
          position: store_location,
          map: map,
          animation: google.maps.Animation.DROP,
          title: 'Hello World!',
          icon: 'https://i.cloudup.com/t2UIuZZrEQ-3000x3000.png',
          visible: true
        });
        marker.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
</script>


<div id="map-canvas"></div>

<div id="funnypic"></div>
<br>
</div>
<br>


<div  id="store_form" class="container">
  <br>
<table id="storedrinks">
  <thead>
    <tr>

      <th><p>Drink Type</p></th>
      <th><p>Picture</p></th>
      <th><p>Price</p></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <% @store.drinks.each do |drink| %>

  <td><%= drink.name %></td>
  <td><img id="drinkpic" src="<%= drink.photo_url %>"></td>
  <td>$ <%= sprintf('%.2f', drink.price(@store.id)) %> </td>

  <td><button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_drink_price_path(drink.drink_price(@store.id)) %> </button></td>
  <td><button type="button" class="btn btn-danger"><%= link_to 'Delete this Drink', drink_price_path(drink.drink_price(@store.id)), method: :delete,
                                    data: { confirm: 'Are you sure?' } %> </td></button>

  </tr>
  <% end %>

</table>


<div id="store_buttons">
  <br>
  <br>
  <button type="button" class="btn btn-success"><a href="https://www.google.com/maps?saddr=My+Location&daddr=<%= @store.address %>" target="_blank">Get Diretions to <%= @store.name %> </a></button>

  <br>
  <br>



<div id="red" class="add_drink_form">

  <p>Add drink to <%= @store.name %></p>
  <% new_drink_price = DrinkPrice.new %>
  <%= form_for new_drink_price do |f|%>
    <input type="hidden" name="drink_price[store_id]" value="<%=@store.id%>">
    <select class="form-control select" name="drink_price[drink_id]" id="drink_price_drink_id">
    <% Drink.all.each do |d| %>
      <% unless @store.drinks.include?(d) %>
        <option value="<%=d.id%>"><%= d.name %></option>
      <% end %>
    <% end %>
  </select>

    <input placeholder="Price" type="text" name="drink_price[price]">
    <br>
    <br>
    <div class="actions"><%= f.submit "Submit" %></div>
  <% end %>


</div>

</div>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users Index</h1>
<% @users.each do |user| %>
  <p>
    <%= user.email %>
    <%= user.password_digest %>
  </p>
<% end %>

app/views/users/new.html.erb
 <h1>Welcome to Caffeine Buddy</h1>
<p>
<img id="buddy" style="margin: 0 auto;" src="https://drive.google.com/thumbnail?id=0B6z5p82sidMKYUE4TlYySnNBLUU&authuser=0&v=1438229609338&sz=w1255-h582" alt=""></p>


<h1>Sign Up</h1>
<div id="red">
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @user.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<br>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<br>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<br>
<%= f.submit "Submit" %>
<!-- <button type="button" class="btn btn-primary"><%#= link_to "Submit", class: 'button' %></button> -->
</div>
<% end %>