config/routes.rb
Rails.application.routes.draw do

  get 'cookies/example_1'

  get 'cookies/example_2'

  get 'cookies/example_3'

  get 'secret/public_info'

  get 'secret/secret'

  root 'sessions#new'

  get 'reviews/index'

  get 'reviews/create'

  get 'reviews/new'

  get 'static_pages/home'

  get '/login', to: 'sessions#new'

resources :sessions, only: [:new, :create, :destroy]

resources :users
resources :stores
resources :drinks
resources :comments
resources :drink_prices
resources :category
resources :static_pages
delete '/logout', to: 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :drinks
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :store
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  has_many :prices
  has_many :stores, through: :prices

  def price(store_id)
    drink = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink
      drink.price
    else
      nil
    end
  end

  def set_price(store_id, new_price)
    drink = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink
      drink.price = new_price
      drink.save
    end
  end

   def drink_price(store_id)
    drink_price = DrinkPrice.find_by(drink: self, store_id: store_id)
    if drink_price
      drink_price
    else
      nil
    end
  end

end

app/models/drink_price.rb
class DrinkPrice < ActiveRecord::Base
  belongs_to :store
  belongs_to :drink
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :drink_prices
  has_many :drinks, through: :drink_prices
  has_many :comments


  geocoded_by :address
  after_validation :geocode, :if => :address_changed?


end

app/models/user.rb
class User < ActiveRecord::Base

 has_secure_password
 validates :email, presence: true, uniqueness: true

 # geocoded_by :ip_address,
 #  :latitude => :lat, :longitude => :lon
 # after_validation :geocode

 def ip_address
  require 'socket'
  Socket::getaddrinfo(Socket.gethostname,"echo",Socket::AF_INET)[0][3]
 end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :authenticate

  def index
    @drinks = Drink.all
  end

  def show
    @drink = Drink.find(params[:id])
  end

  def edit
    @drink = Drink.find(params[:id])
  end

  def update
    @drink = Drink.find(params[:id])
    @drink.update_attributes(drink_params)
    redirect_to drinks_path
  end

  def new
    @drink = Drink.new
  end

 def create
  @drink = Drink.new(drink_params)
  if @drink.save
   redirect_to drinks_path
  else
   render 'new'
  end
 end

  def destroy
    drink = Drink.find(params[:id])
    drink.destroy
    redirect_to drinks_path
  end

  private

  def drink_params
    params.require(:drink).permit(:name, :photo_url,)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: :edit

 def index
  @users = User.all
 end

 def show

 end

 def new
  @user = User.new
 end

 def create
  @user = User.new(user_params)
  if @user.save
   redirect_to login_path
  else
   render 'new'
  end
 end

 private

 def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/drink_prices_helper.rb
module DrinkPricesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaffeineBuddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render "shared/header" %>
  <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= message %>
    </div>
  <% end %>

<%= yield %>
 <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.erb
<footer>

<p id="footer">
   <img id="copy" src="http://www2.psd100.com/ppp/2013/11/2701/copyright-symbol-1127234250.png" alt="">

   Caffeine Buddy</p>
</footer>

app/views/shared/_header.html.erb
<header>
 <div class="navbar">

  <%= link_to 'Home', static_pages_path %>
  <%= link_to 'Stores', stores_path %>
  <div id="logout">
  <%= link_to 'Logout', logout_path, method: :delete, data: {confirm: "Are you sure?"} %>
  </div>

</div>
</header>